//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 10:15:52 PM IST 
//


package com.ritaum.travel.galileo.xmlselect;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ritaum.travel.galileo.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _String_QNAME = new QName("http://webservices.galileo.com", "string");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ritaum.travel.galileo.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubmitXml }
     * 
     */
    public SubmitXml createSubmitXml() {
        return new SubmitXml();
    }

    /**
     * Create an instance of {@link SubmitXmlResponse }
     * 
     */
    public SubmitXmlResponse createSubmitXmlResponse() {
        return new SubmitXmlResponse();
    }

    /**
     * Create an instance of {@link MultiSubmitXml }
     * 
     */
    public MultiSubmitXml createMultiSubmitXml() {
        return new MultiSubmitXml();
    }

    /**
     * Create an instance of {@link MultiSubmitXmlResponse }
     * 
     */
    public MultiSubmitXmlResponse createMultiSubmitXmlResponse() {
        return new MultiSubmitXmlResponse();
    }

    /**
     * Create an instance of {@link SubmitXmlOnSession }
     * 
     */
    public SubmitXmlOnSession createSubmitXmlOnSession() {
        return new SubmitXmlOnSession();
    }

    /**
     * Create an instance of {@link SubmitXmlOnSessionResponse }
     * 
     */
    public SubmitXmlOnSessionResponse createSubmitXmlOnSessionResponse() {
        return new SubmitXmlOnSessionResponse();
    }

    /**
     * Create an instance of {@link GetIdentityInfoResponse }
     * 
     */
    public GetIdentityInfoResponse createGetIdentityInfoResponse() {
        return new GetIdentityInfoResponse();
    }

    /**
     * Create an instance of {@link SubmitCruiseTransaction }
     * 
     */
    public SubmitCruiseTransaction createSubmitCruiseTransaction() {
        return new SubmitCruiseTransaction();
    }

    /**
     * Create an instance of {@link SubmitCruiseTransactionResponse }
     * 
     */
    public SubmitCruiseTransactionResponse createSubmitCruiseTransactionResponse() {
        return new SubmitCruiseTransactionResponse();
    }

    /**
     * Create an instance of {@link SubmitXml.Request }
     * 
     */
    public SubmitXml.Request createSubmitXmlRequest() {
        return new SubmitXml.Request();
    }

    /**
     * Create an instance of {@link SubmitXml.Filter }
     * 
     */
    public SubmitXml.Filter createSubmitXmlFilter() {
        return new SubmitXml.Filter();
    }

    /**
     * Create an instance of {@link SubmitXmlResponse.SubmitXmlResult }
     * 
     */
    public SubmitXmlResponse.SubmitXmlResult createSubmitXmlResponseSubmitXmlResult() {
        return new SubmitXmlResponse.SubmitXmlResult();
    }

    /**
     * Create an instance of {@link MultiSubmitXml.Requests }
     * 
     */
    public MultiSubmitXml.Requests createMultiSubmitXmlRequests() {
        return new MultiSubmitXml.Requests();
    }

    /**
     * Create an instance of {@link MultiSubmitXmlResponse.Responses }
     * 
     */
    public MultiSubmitXmlResponse.Responses createMultiSubmitXmlResponseResponses() {
        return new MultiSubmitXmlResponse.Responses();
    }

    /**
     * Create an instance of {@link BeginSession }
     * 
     */
    public BeginSession createBeginSession() {
        return new BeginSession();
    }

    /**
     * Create an instance of {@link BeginSessionResponse }
     * 
     */
    public BeginSessionResponse createBeginSessionResponse() {
        return new BeginSessionResponse();
    }

    /**
     * Create an instance of {@link EndSession }
     * 
     */
    public EndSession createEndSession() {
        return new EndSession();
    }

    /**
     * Create an instance of {@link EndSessionResponse }
     * 
     */
    public EndSessionResponse createEndSessionResponse() {
        return new EndSessionResponse();
    }

    /**
     * Create an instance of {@link SubmitXmlOnSession.Request }
     * 
     */
    public SubmitXmlOnSession.Request createSubmitXmlOnSessionRequest() {
        return new SubmitXmlOnSession.Request();
    }

    /**
     * Create an instance of {@link SubmitXmlOnSession.Filter }
     * 
     */
    public SubmitXmlOnSession.Filter createSubmitXmlOnSessionFilter() {
        return new SubmitXmlOnSession.Filter();
    }

    /**
     * Create an instance of {@link SubmitXmlOnSessionResponse.SubmitXmlOnSessionResult }
     * 
     */
    public SubmitXmlOnSessionResponse.SubmitXmlOnSessionResult createSubmitXmlOnSessionResponseSubmitXmlOnSessionResult() {
        return new SubmitXmlOnSessionResponse.SubmitXmlOnSessionResult();
    }

    /**
     * Create an instance of {@link SubmitTerminalTransaction }
     * 
     */
    public SubmitTerminalTransaction createSubmitTerminalTransaction() {
        return new SubmitTerminalTransaction();
    }

    /**
     * Create an instance of {@link SubmitTerminalTransactionResponse }
     * 
     */
    public SubmitTerminalTransactionResponse createSubmitTerminalTransactionResponse() {
        return new SubmitTerminalTransactionResponse();
    }

    /**
     * Create an instance of {@link GetIdentityInfo }
     * 
     */
    public GetIdentityInfo createGetIdentityInfo() {
        return new GetIdentityInfo();
    }

    /**
     * Create an instance of {@link GetIdentityInfoResponse.GetIdentityInfoResult }
     * 
     */
    public GetIdentityInfoResponse.GetIdentityInfoResult createGetIdentityInfoResponseGetIdentityInfoResult() {
        return new GetIdentityInfoResponse.GetIdentityInfoResult();
    }

    /**
     * Create an instance of {@link SubmitCruiseTransaction.Transactions }
     * 
     */
    public SubmitCruiseTransaction.Transactions createSubmitCruiseTransactionTransactions() {
        return new SubmitCruiseTransaction.Transactions();
    }

    /**
     * Create an instance of {@link SubmitCruiseTransactionResponse.Response }
     * 
     */
    public SubmitCruiseTransactionResponse.Response createSubmitCruiseTransactionResponseResponse() {
        return new SubmitCruiseTransactionResponse.Response();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.galileo.com", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

}
